services:
  - type: web
    name: pharma-mobile-backend
    env: python
    plan: free
    runtime: python-3.11

    buildCommand: pip install -r requirements_backend.txt
    startCommand: gunicorn -w 2 backend_main:app --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

    healthCheckPath: /health
